export const networkItems = [
  {
    id: 'all',
    name: 'All Networks',
    color: '#8a92a6',
    icon: '◎',
    featured: true,
  },
  {
    id: 'bsc',
    name: 'BSC',
    color: '#f3ba2f',
    icon: '◆',
    featured: true,
  },
  {
    id: 'solana',
    name: 'Solana',
    color: '#14f195',
    icon: '≋',
    featured: true,
  },
  {
    id: 'base',
    name: 'Base',
    color: '#0052ff',
    icon: '●',
    featured: true,
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    color: '#dfe3eb',
    icon: '◆',
    featured: true,
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    color: '#28a0f0',
    icon: '◈',
    featured: false,
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    color: '#e84142',
    icon: '▲',
    featured: false,
  },
  {
    id: 'polygon',
    name: 'Polygon',
    color: '#8247e5',
    icon: '⬡',
    featured: false,
  },
  {
    id: 'optimism',
    name: 'Optimism',
    color: '#ff0420',
    icon: '○',
    featured: false,
  },
  {
    id: 'sui',
    name: 'Sui',
    color: '#4da2ff',
    icon: '◉',
    featured: false,
  },
  {
    id: 'aptos',
    name: 'Aptos',
    color: '#222222',
    icon: '⬢',
    featured: false,
  },
  {
    id: 'cardano',
    name: 'Cardano',
    color: '#0033ad',
    icon: '✣',
    featured: false,
  },
  {
    id: 'ton',
    name: 'TON',
    color: '#0098ea',
    icon: '💎',
    featured: false,
  },
  {
    id: 'near',
    name: 'Near',
    color: '#000000',
    icon: 'Ⓝ',
    featured: false,
  },
  {
    id: 'flare-network',
    name: 'Flare Network',
    color: '#e62058',
    icon: '🔥',
    featured: false,
  },
  {
    id: 'ethpow',
    name: 'EthereumPoW',
    color: '#627eea',
    icon: '⚡',
    featured: false,
  },
  {
    id: 'ethereum-classic',
    name: 'Ethereum Classic',
    color: '#328332',
    icon: '❖',
    featured: false,
  },
  {
    id: 'fuel-network',
    name: 'Fuel Network',
    color: '#00f58c',
    icon: '⛽',
    featured: false,
  },
  {
    id: 'plasma',
    name: 'Plasma',
    color: '#8247e5',
    icon: '⚡',
    featured: false,
  },
  {
    id: 'juchain',
    name: 'JuChain',
    color: '#6366f1',
    icon: '⬡',
    featured: false,
  },
  {
    id: 'somnia',
    name: 'Somnia',
    color: '#9333ea',
    icon: '✦',
    featured: false,
  },
  {
    id: 'monad',
    name: 'Monad',
    color: '#836ef9',
    icon: '💜',
    featured: false,
  },
  {
    id: 'katana',
    name: 'Katana',
    color: '#dc2626',
    icon: '⚔️',
    featured: false,
  },
  {
    id: 'ink',
    name: 'Ink',
    color: '#000000',
    icon: '🖋️',
    featured: false,
  },
  {
    id: 'megaeth',
    name: 'MegaETH',
    color: '#3b82f6',
    icon: '⚡',
    featured: false,
  },
  {
    id: 'bevm',
    name: 'BEVM',
    color: '#f7931a',
    icon: '₿',
    featured: false,
  },
  {
    id: 'zklink-nova',
    name: 'zkLink Nova',
    color: '#0025f5',
    icon: '🌟',
    featured: false,
  },
  {
    id: 'krown',
    name: 'Krown',
    color: '#eab308',
    icon: '👑',
    featured: false,
  },
  {
    id: 'kiteai',
    name: 'KiteAI',
    color: '#06b6d4',
    icon: '🪁',
    featured: false,
  },
  {
    id: 'tempo',
    name: 'Tempo',
    color: '#10b981',
    icon: '⏱️',
    featured: false,
  },
  {
    id: 'anubis',
    name: 'Anubis',
    color: '#d97706',
    icon: '🐕',
    featured: false,
  },
  {
    id: 'onyx',
    name: 'Onyx',
    color: '#1f2937',
    icon: '⬛',
    featured: false,
  },
  {
    id: 'robinhood',
    name: 'Robinhood',
    color: '#00c805',
    icon: '🏹',
    featured: false,
  },
  {
    id: 'stable',
    name: 'Stable',
    color: '#14b8a6',
    icon: '⚖️',
    featured: false,
  },
] as const;

export type NetworkItem = (typeof networkItems)[number];
export type NetworkId = NetworkItem['id'];

export const featuredNetworkItems = networkItems.filter(
  (network) => network.featured,
);
